### ISSUE TITLE
WebControlExtension.Exists() fails when control does not exist

### ISSUE THREAD

**Issue by nortimirino93** [Unicorn-TAF/ui-web#17]
Fails on getting control.Instance
Throws ControlNotFound

**Comment by dobriyanchik** [comment]
Confirm, code fails in case when control is absent. It appears that the extension is obsolete (forgot to mark it).

There is a new UI agnostic extension appeared in [UI.Core](https://github.com/Unicorn-TAF/ui-core/releases/tag/ui.core-3.1) lib starting from version 3.1.0. @nortimirino93 please use it instead.

`Unicorn.UI.Core.PageObject.ControlExtension.ExistsInPageObject`
